# This docker-compose file is for spinning up a blockstack-core node
version: '2'
services:
  blockstack-core:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './data/core/server/:/root/.blockstack-server/'
    restart: always
    ports:
      - "6264:6264"
    networks:
      - "api"
      
networks:
  api: null
