version: '2'
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - './data/mongodb/:/data/db'
    networks:
      - api
    restart: always

  search-indexer:
    build:
      context: ../
      dockerfile: api/search/Dockerfile
    environment:
      - BLOCKSTACK_DEBUG=0
      - PUBLIC_NODE=True
      - DEFAULT_HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb
    networks:
      - api
    restart: always
    links:
      - mongodb
      - blockstack-core
    volumes:
      - "./data/search-api:/var/blockstack-search"
      - "/etc/localtime:/etc/localtime:ro"

  search-api:
    build:
      context: ../
      dockerfile: api/Dockerfile
    environment:
      - BLOCKSTACK_DEBUG=1
      - PUBLIC_NODE=True
      - DEFAULT_HOST=0.0.0.0
      - BSK_API_TMPLTDIR=/src/blockstack/api/templates
      - DEFAULT_CACHE_TIMEOUT=1800
      - MONGODB_URI=mongodb://mongodb
      - BASE_API_URL=http://blockstack-core:6270
      - DEBUG=True
    networks:
      - api
    ports:
      - 3000:3000
    restart: always
    links:
      - mongodb
    volumes:
      - "./data/search-api:/var/blockstack-search"
 
  blockstack-core:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - './blockstack-core/server/:/root/.blockstack-server/'
    restart: always
    networks: 
      - api
  
networks:
  api: null
